### ISSUE TITLE
Bloomfilter bit collision

### ISSUE THREAD

**Issue by wilsonbredaneto** [vla/BloomFilter.NetCore#7]
Hi,
can you explain for me how does bloomfilter deal with bit collision and how we can prevent that?

Tks,
Wilson

**Comment by vla** [comment]
hi @wilsonbredaneto ,

Conflicting scale parameters can be customized ‘ErrorRate=0.01’, You can reset 'Clear' when the desired element is close to 90%.

```cs
var bf = FilterBuilder.Build(10000000, 0.01);

long count = 0;
if (bf.Add("AAAA"))
{
    count++;
}
if (count > 10000000 * 0.9)
    bf.Clear();
```
