### ISSUE TITLE
Remove uint usage (CLS)

### ISSUE THREAD

**Issue by timaiv** [vla/BloomFilter.NetCore#8]
https://github.com/vla/BloomFilter.NetCore/blob/0036a2c007fbb8419b3bbf86a8c6335f4209ed25/src/BloomFilter/FilterBuilder.cs#LL14C38-L14C43

`uint` is not CLS-compliant.
Ex: `StringBuilder(Int32)`, `List<T>(Int32)` etc

https://learn.microsoft.com/en-us/dotnet/standard/language-independence#types-and-type-member-signatures

**Comment by vla** [comment]
Much appreciated, thx
